title: AG Talks
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  anandhu-gopi
linkedin_username: anandhu-gopi-691b35144
remote_theme: "mmistakes/minimal-mistakes@4.24.0"

header_pages:
  - portfolio.md

# Build settings
theme: minimal-mistakes-jekyll

#Minimal Mistakes 
email: anandhu.gopi97@gmail.com
minimal_mistakes_skin: "neon"
name: "Anandhu Gopi"
description: "Anandhu Gopi's Blog"
date_format: "%Y-%m-%d"
enable_copy_code_button: true
search: true # enable search on website
timezone: 	Asia/Calcutta
powered_by: false

pagination:
  enabled: true
  collection: 'posts'
  per_page: 5
  permalink: '/page/:num/'  # Pages are index.html inside this folder (default)
  title: ':title - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  trail:
    before: 2
    after: 2
lunr:
  search_within_pages: true # to have search on all pages

defaults:
  # _posts setting post font matter defaults
  - scope:
      path: ""
      type: posts
    values:
      show_date: true
      read_time: true
      comments: true
      share: true

author:
  name     : "Anandhu Gopi"
  avatar   : "/assets/images/avatar.png"
  bio      : "Engineer — loves to talk ideas and listen to stories"
  location : "India"
  links:
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/anandhu-gopi-691b35144"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/anandhu-gopi"

footer:
  since: "1997"
  links:
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/anandhu-gopi-691b35144"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/anandhu-gopi"


include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
